apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ledger-graph
    tier: api
  name: ledger-graph-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ledger-graph
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ledger-graph
      name: ledger-graph
    spec:
      containers:
      - env:
        - name: MOUNT_PATH
          value: /ledger
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: user
              name: db-credentials
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              key: password
              name: db-credentials
        image: gcr.io/api-dannydavidson-com/ledger-graph:{{LEDGER_GRAPH_VERSION}}
        imagePullPolicy: Always
        name: ledger-graph
        ports:
        - containerPort: 11235
          name: ledger-graph
          protocol: TCP
        resources:
          limits:
            cpu: 500m
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: ledger-graph
  name: ledger-graph
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 11235
    nodePort: 32346
  selector:
    app: ledger-graph
  sessionAffinity: None
  type: NodePort
